name: Build IbraSoft ERP App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Android App
        uses: pwabuilder/pwabuilder-android@main
        with:
          manifest_url: https://engibrahimalhammadi-jpg.github.io/ibrasoft-erp/manifest.json
